// Code generated by protoc-gen-go. DO NOT EDIT.
// source: article.proto

package boltsec

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ProtobufArticle struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProtobufArticle) Reset()         { *m = ProtobufArticle{} }
func (m *ProtobufArticle) String() string { return proto.CompactTextString(m) }
func (*ProtobufArticle) ProtoMessage()    {}
func (*ProtobufArticle) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c593d380f9840a2, []int{0}
}

func (m *ProtobufArticle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProtobufArticle.Unmarshal(m, b)
}
func (m *ProtobufArticle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProtobufArticle.Marshal(b, m, deterministic)
}
func (m *ProtobufArticle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProtobufArticle.Merge(m, src)
}
func (m *ProtobufArticle) XXX_Size() int {
	return xxx_messageInfo_ProtobufArticle.Size(m)
}
func (m *ProtobufArticle) XXX_DiscardUnknown() {
	xxx_messageInfo_ProtobufArticle.DiscardUnknown(m)
}

var xxx_messageInfo_ProtobufArticle proto.InternalMessageInfo

func (m *ProtobufArticle) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *ProtobufArticle) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func init() {
	proto.RegisterType((*ProtobufArticle)(nil), "boltsec.ProtobufArticle")
}

func init() {
	proto.RegisterFile("article.proto", fileDescriptor_5c593d380f9840a2)
}

var fileDescriptor_5c593d380f9840a2 = []byte{
	// 95 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0x2c, 0x2a, 0xc9,
	0x4c, 0xce, 0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4f, 0xca, 0xcf, 0x29, 0x29,
	0x4e, 0x4d, 0x56, 0x32, 0xe7, 0xe2, 0x0f, 0x00, 0x89, 0x24, 0x95, 0xa6, 0x39, 0x42, 0x54, 0x08,
	0xf1, 0x71, 0x31, 0x79, 0xba, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x01, 0x59, 0x42, 0x22,
	0x5c, 0xac, 0x21, 0x99, 0x25, 0x39, 0xa9, 0x12, 0x4c, 0x60, 0x21, 0x08, 0x27, 0x89, 0x0d, 0x6c,
	0x90, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x08, 0x7c, 0x6c, 0x17, 0x59, 0x00, 0x00, 0x00,
}
